# Generated by Django 5.1 on 2024-10-20 14:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practise',
            name='id',
        ),
        migrations.AddField(
            model_name='practise',
            name='big_auto_field',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='practise',
            name='big_integer_field',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practise',
            name='binary_field',
            field=models.BinaryField(default=1),
        ),
        migrations.AddField(
            model_name='practise',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='practise',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='practise',
            name='date_time_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='practise',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='practise',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='practise',
            name='email_field',
            field=models.EmailField(default='anik12@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='practise',
            name='float_field',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='practise',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='practise',
            name='json_field',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practise',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practise',
            name='small_integer_field',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practise',
            name='text_field',
            field=models.TextField(default='Gen-z'),
        ),
        migrations.AddField(
            model_name='practise',
            name='time_field',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='practise',
            name='url_field',
            field=models.URLField(default='http:www.youtube.com'),
        ),
        migrations.AddField(
            model_name='practise',
            name='uuid_field',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
